docker_repo: docker-ce.repo
docker_user: ublanon

web_docker_img_name: web
web_docker_img_tag: latest
web_container_name: webserver
web_ports: 8080:8080
web_dockerfile_path: docker/web/

db_docker_img_name: db
db_docker_img_tag: latest
db_container_name: dbserver
db_ports: 33061:33061
db_dockerfile_path: docker/db/
